### ISSUE TITLE
Cached node_modules layer with native extensions reused even when version of node changes

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/yarn-install#144]
## What happened?

* What were you attempting to do?
I wanted to rebuild an app that uses`bcrypt` native extension after bumping the node engine version used for the app.
 
* What did you expect to happen?
I expected the `node_modules` to be rebuilt (so that the native extension is rebuilt) and is runnable against the new version of node.

* What was the actual behavior? Please provide log output, if possible.
```
‣ cat buildpack.yml
---
nodejs:
  version: ^12.12.0

‣ pack build with-bcrypt  -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.37-full --clear-cache
0.1.37-full: Pulling from paketobuildpacks/builder
Digest: sha256:576cb792b7362f084d75f1855d0a8ba7a9c71855feef3ee711ff539ca085a551
Status: Image is up to date for paketobuildpacks/builder:0.1.37-full
full-cnb: Pulling from paketobuildpacks/run
Digest: sha256:b6249cb47b83fb9ea24b10a7a6a1cff4e1b6a4c78b8f5c686bd9b66a2c9d135c
Status: Image is up to date for paketobuildpacks/run:full-cnb
0.0.10: Pulling from paketo-buildpacks/nodejs
Digest: sha256:4b723c77e6313b7d283fc0e1c2745979a88930935b05f9a2268023b3cb45d7db
Status: Image is up to date for gcr.io/paketo-buildpacks/nodejs:0.0.10
0.9.3: Pulling from buildpacksio/lifecycle
Digest: sha256:bc253af2edf1577717618cb3a95f0f16bb18fc9e804efbcc1b85f657d931a757
Status: Image is up to date for buildpacksio/lifecycle:0.9.3
===> DETECTING
[detector] paketo-buildpacks/node-engine  0.1.2
[detector] paketo-buildpacks/yarn         0.0.2
[detector] paketo-buildpacks/yarn-install 0.2.0
[detector] paketo-buildpacks/yarn-start   0.0.2
===> ANALYZING
[analyzer] Warning: Not restoring cached layer metadata, no cache flag specified.
[analyzer] Previous image with name "index.docker.io/library/with-bcrypt:latest" not found
[analyzer] Skipping buildpack layer analysis
===> RESTORING
Skipping 'restore' due to clearing cache
===> BUILDING
[builder] Paketo Node Engine Buildpack 0.1.2
[builder]   Resolving Node Engine version
[builder]     Candidate version sources (in priority order):
[builder]       buildpack.yml -> "^12.12.0"
[builder]                     -> ""
[builder]       <unknown>     -> "*"
[builder]
[builder]     Selected Node Engine version (using buildpack.yml): 12.19.0
[builder]
[builder]   Executing build process
[builder]     Installing Node Engine 12.19.0
[builder]       Completed in 1.445s
...
...
...
[builder] Paketo Yarn Install Buildpack 0.2.0
[builder]   Resolving installation process
[builder]     Process inputs:
[builder]       yarn.lock -> Found
[builder]
[builder]     Selected default build process: 'yarn install'
[builder]
[builder]   Executing build process
[builder]     Running yarn install --ignore-engines --frozen-lockfile --modules-folder /layers/paketo-buildpacks_yarn-install/modules/node_modules
[builder]       Completed in 5.818s
...
...
...
Successfully built image with-bcrypt

 ‣ docker run -d --env PORT=8080 --publish 8080:8080 with-bcrypt
7e5b88f8658d512d293596f9410c37d6b71e5db1be96e2193ba100b196b5237e

 ‣ curl 0.0.0.0:8080
Hello, World!
```
Then, change version of node and rebuild:
```
 ‣ cat buildpack.yml
---
nodejs:
  version: ^14.0.0

 ‣ pack build with-bcrypt  -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.37-full
0.1.37-full: Pulling from paketobuildpacks/builder
Digest: sha256:576cb792b7362f084d75f1855d0a8ba7a9c71855feef3ee711ff539ca085a551
Status: Image is up to date for paketobuildpacks/builder:0.1.37-full
full-cnb: Pulling from paketobuildpacks/run
Digest: sha256:b6249cb47b83fb9ea24b10a7a6a1cff4e1b6a4c78b8f5c686bd9b66a2c9d135c
Status: Image is up to date for paketobuildpacks/run:full-cnb
0.0.10: Pulling from paketo-buildpacks/nodejs
Digest: sha256:4b723c77e6313b7d283fc0e1c2745979a88930935b05f9a2268023b3cb45d7db
Status: Image is up to date for gcr.io/paketo-buildpacks/nodejs:0.0.10
0.9.3: Pulling from buildpacksio/lifecycle
Digest: sha256:bc253af2edf1577717618cb3a95f0f16bb18fc9e804efbcc1b85f657d931a757
Status: Image is up to date for buildpacksio/lifecycle:0.9.3
===> DETECTING
[detector] paketo-buildpacks/node-engine  0.1.2
[detector] paketo-buildpacks/yarn         0.0.2
[detector] paketo-buildpacks/yarn-install 0.2.0
[detector] paketo-buildpacks/yarn-start   0.0.2
===> ANALYZING
[analyzer] Restoring metadata for "paketo-buildpacks/node-engine:node" from app image
[analyzer] Restoring metadata for "paketo-buildpacks/yarn:yarn" from cache
[analyzer] Restoring metadata for "paketo-buildpacks/yarn-install:modules" from app image
===> RESTORING
[restorer] Restoring data for "paketo-buildpacks/node-engine:node" from cache
[restorer] Restoring data for "paketo-buildpacks/yarn:yarn" from cache
[restorer] Restoring data for "paketo-buildpacks/yarn-install:modules" from cache
===> BUILDING
[builder] Paketo Node Engine Buildpack 0.1.2
[builder]   Resolving Node Engine version
[builder]     Candidate version sources (in priority order):
[builder]       buildpack.yml -> "^14.0.0"
[builder]                     -> ""
[builder]       <unknown>     -> "*"
[builder]
[builder]     Selected Node Engine version (using buildpack.yml): 14.13.0
[builder]
[builder]   Executing build process
[builder]     Installing Node Engine 14.13.0
[builder]       Completed in 2.108s
...
...
...
[builder] Paketo Yarn Install Buildpack 0.2.0
[builder]   Resolving installation process
[builder]     Process inputs:
[builder]       yarn.lock -> Found
[builder]
[builder]     Selected default build process: 'yarn install'
[builder]
[builder]   Reusing cached layer /layers/paketo-buildpacks_yarn-install/modules
...
...
...
Successfully built image with-bcrypt

 ‣ docker run -d --env PORT=8080 --publish 8080:8080 with-bcrypt
a6ae0e4df0b8d23c3a9a48240bd9c278b6482b6a9072b16ff2ddbb434b1fa85c
Tue Nov 17 22:55:00 6 jobs ~/workspace/paketo-buildpacks/yarn-install/integration/testdata/yarn_pre_gyp [main: 1?]
 ‣ curl 0.0.0.0:8080
curl: (7) Failed to connect to 0.0.0.0 port 8080: Connection refused

‣ docker logs a6ae0e4df0b8d23c3a9a48240bd9c278b6482b6a9072b16ff2ddbb434b1fa85c
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/layers/paketo-buildpacks_yarn-install/modules/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/layers/paketo-buildpacks_yarn-install/modules/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
```
## Build Configuration

Please provide some details about your build configuration.

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you using? Please include a version.
```
 ‣ pack --version
0.13.1+git-4134cc6.build-1135
```

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
Can reproduce the issue with [this sample app](https://github.com/paketo-buildpacks/yarn-install/tree/main/integration/testdata/yarn_pre_gyp) and the addition of `buildpack.yml` as described in the above log output.

## Checklist

Please confirm the following:

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by fg-j** [comment]
Rebuilding the app with the same config, but with `--clear-cache` resolves the runtime error:
```
 ‣ cat buildpack.yml
---
nodejs:
  version: ^14.0.0

 ‣ pack build with-bcrypt  -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.37-full --clear-cache
...
...
...
[builder] Paketo Yarn Install Buildpack 0.2.0
[builder]   Resolving installation process
[builder]     Process inputs:
[builder]       yarn.lock -> Found
[builder]
[builder]     Selected default build process: 'yarn install'
[builder]
[builder]   Executing build process
[builder]     Running yarn install --ignore-engines --frozen-lockfile --modules-folder /layers/paketo-buildpacks_yarn-install/modules/node_modules
[builder]       Completed in 6.04s
...
...
...
Successfully built image with-bcrypt

 ‣ docker run -d --env PORT=8080 --publish 8080:8080 with-bcrypt
3287fc3d043899bf901b7036fc4e589e2f1e52eb211a8c7cbb8a22ce7ef28efb

 ‣ curl 0.0.0.0:8080
Hello, World!
```

**Comment by arjun024** [comment]
@fg-j This should be solved by https://github.com/paketo-buildpacks/yarn-install/pull/179 and available in the latest `yarn-install` buildpack. 

See https://github.com/paketo-buildpacks/yarn-install/issues/128#issuecomment-786727038 `'user-agent'` should account for the `yarn` and `node` versions used in the build.

Feel free to reopen if the issue still persist.
